### ISSUE TITLE
I'm currently experiencing a 502 Bad Gateway error accessing rpc.elaeth.io

### ISSUE THREAD

**Issue by JulianNicholls** [crregions/ela-eth-sidechain-doc#1]
I have everything set up as specified  on the  `Home > Build > Browser dApps > Environment Setup > Test Net Setup` page (and here). i.e.

`elaethTest: {
      host: 'https://rpc.elaeth.io',
      port: 8545,
      network_id: '*',
      provider: () => new HDWalletProvider(mnemonic, 'https://rpc.elaeth.io'),
      gasLimit: 8000000,
      gasPrice: 1000000000,
    },`

When I type `truffle console --network elaethTest,` I get this

`/home/julian/sources/Clockd/elastos/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:57
          const err = new Error(msg)
                      ^
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
Error: Unknown Error: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

    at Request._callback (/home/julian/sources/Clockd/elastos/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:57:23)
    at Request.self.callback (/home/julian/sources/Clockd/elastos/node_modules/request/request.js:185:22)
    at Request.emit (node:events:379:20)
    at Request.EventEmitter.emit (node:domain:470:12)
    at Request.<anonymous> (/home/julian/sources/Clockd/elastos/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:379:20)
    at Request.EventEmitter.emit (node:domain:470:12)
    at IncomingMessage.<anonymous> (/home/julian/sources/Clockd/elastos/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:485:28)
    at IncomingMessage.emit (node:events:391:22)
    at IncomingMessage.EventEmitter.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
    at PollingBlockTracker._performSync (/home/julian/sources/Clockd/elastos/node_modules/eth-block-tracker/src/polling.js:51:24)`

**Comment by crregions** [comment]
Thanks we'll check.

**Comment by JulianNicholls** [comment]
In addition, testnet.elaeth.io gives a 502 Bad Gateway, 
and faucet.elaeth.io gives a Cloudflare error 1014 - CNAME Cross-User Banned.
